# Generated by Django 3.2.6 on 2021-09-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_list',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='donor_list',
            name='blood',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='donor_list',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donor_list',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='donor_list',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donor_list',
            name='phn',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user_list',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='user_list',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='user_list',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='user_list',
            name='repassword',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
