# Generated by Django 3.2.6 on 2021-10-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_auto_20211001_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor_list',
            name='user_id',
        ),
    ]
